# Generated by Django 6.0.4 on 2026-05-04 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_validez', models.DateField()),
                ('token', models.CharField(blank=True, max_length=255, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEscaneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escaneos', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Historial de Escaneo',
                'verbose_name_plural': 'Historial de Escaneos',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
