# Generated by Django 6.0.4 on 2026-05-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(default='', max_length=255),
        ),
    ]
